sidus_eav_model:
  data_class: AppBundle\Entity\Order
  value_class: AppBundle\Entity\OrderAttributeValue
  families:
      Invoice:
        data_class: AppBundle\Entity\Invoice
        value_class: AppBundle\Entity\InvoiceAttributeValue
        attributeAsLabel: title
        attributes:
          title: # Default type is string
            required: true
          content:
            type: text
          publicationDate:
            type: datetime
          publicationStatus:
            type: choice
            form_options: # Symfony form options are passed directly
              choices:
                draft: Draft
                published: Published
                archived: Archived
          isFeatured:
            type: boolean
